parameters:
     amara_one_hydra.api.default.class: Amara\OneHydra\Api
     amara_one_hydra.api.http_request_builder.default.class: Amara\OneHydra\Http\HttpRequestBuilder
     amara_one_hydra.api.transport.guzzle.class: Amara\OneHydra\Http\Transport\GuzzleTransport
     amara_one_hydra.api.result_builder_engine.default.class: Amara\OneHydra\ResultBuilder\ResultBuilderEngine
     amara_one_hydra.page_manager.default.class: Amara\Bundle\OneHydraBundle\Service\PageManager
     twig.onehydra_extension.default.class: Amara\Bundle\OneHydraBundle\Twig\Extension\OneHydraExtension
     amara_one_hydra.listener.default.class: Amara\Bundle\OneHydraBundle\EventListener\OneHydraListener
     amara_one_hydra.page_storage.default.class: Amara\Bundle\OneHydraBundle\Storage\PageStorage
     amara_one_hydra.page_transform_strategy.default.class: Amara\Bundle\OneHydraBundle\Strategy\DefaultPageTransformStrategy

services:
    amara_one_hydra.api.default:
        class: '%amara_one_hydra.api.default.class%'
        arguments: ['@amara_one_hydra.api.http_request_builder', '@amara_one_hydra.api.transport', '@amara_one_hydra.api.result_builder_engine']

    amara_one_hydra.api.http_request_builder.default:
        class: '%amara_one_hydra.api.http_request_builder.default.class%'
        # We're setting the auth token for each program via request attributes
        # so we leave it blank here
        arguments: ['%amara_one_hydra.is_uat%', '']

    amara_one_hydra.api.transport.guzzle:
        class: '%amara_one_hydra.api.transport.guzzle.class%'
        public: true
        arguments: ['@amara_one_hydra.api.guzzle_client']

    amara_one_hydra.api.result_builder_engine.default:
        class: '%amara_one_hydra.api.result_builder_engine.default.class%'

    amara_one_hydra.api.guzzle_client:
        class: GuzzleHttp\Client
        public: true
        arguments: [{defaults: {verify: '%amara_one_hydra.is_not_uat%'}}]

    amara_one_hydra.page_manager.default:
        class: '%amara_one_hydra.page_manager.default.class%'
        calls:
            - [setPageStorage, ['@amara_one_hydra.page_storage']]
            - [setPageTransformStrategy, ['@amara_one_hydra.page_transform_strategy']]

    amara_one_hydra.page_storage.default:
        class: '%amara_one_hydra.page_storage.default.class%'
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    amara_one_hydra.page_transform_strategy.default:
        class: '%amara_one_hydra.page_transform_strategy.default.class%'

    twig.onehydra_extension.default:
        class: '%twig.onehydra_extension.default.class%'
        public: true
        calls:
            - [setRequestStack, ['@request_stack']]
            - [setPageManager, ['@amara_one_hydra.page_manager']]
        tags: 
            - { name: twig.extension }

    kernel.listeners.onehydra_listener.default:
        class: '%amara_one_hydra.listener.default.class%'
        calls:
            - [setPageManager, ['@amara_one_hydra.page_manager']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}