parameters:
     amara_one_hydra.pagemanager.class: Amara\Bundle\OneHydraBundle\Service\PageManager
     amara_one_hydra.twig_ext.class: Amara\Bundle\OneHydraBundle\Twig\Extension\OneHydraExtension
     amara_one_hydra.listener.class: Amara\Bundle\OneHydraBundle\EventListener\OneHydraListener
     amara_one_hydra.program_solver_strategy.class: Amara\Bundle\OneHydraBundle\Strategy\EmptyProgramSolverStrategy
     amara_one_hydra.pageproxy: Amara\Bundle\OneHydraBundle\Proxy\PageProxy
     amara_one_hydra.current_page_state.class: Amara\Bundle\OneHydraBundle\State\CurrentPageState

services:
    onehydra_pagemanager:
        class: %amara_one_hydra.pagemanager.class%
        calls:
            - [setPageProxy, [@onehydra_pageproxy]]
            - [setProgramSolverStrategy, [@onehydra_program_solver_strategy]]

    onehydra_pageproxy:
        class: %amara_one_hydra.pageproxy%
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager]]

    onehydra_current_page_state:
        class: %amara_one_hydra.current_page_state.class%

    onehydra_program_solver_strategy:
        class: %amara_one_hydra.program_solver_strategy.class%

    twig.onehydra_extension:
        class: %amara_one_hydra.twig_ext.class%
        arguments: [@request_stack]
        calls:
            - [setPageManager, [@onehydra_pagemanager]]
        tags: 
            - { name: twig.extension }


    kernel.listeners.onehydra_listener:
        class: %amara_one_hydra.listener.class%
        calls:
            - [setPageManager, [@onehydra_pagemanager]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}